"""Runtime wrapper and CPU adapter for manual-cubic MIGraphX resize + NMS + TopK heads.

The compiled .mxr program is generated by
``modules.migraphx_manual_cubic_topk_compiler`` and expects low-resolution
NCHW heatmaps:

    input:  heatmaps [1, 18, in_h, in_w] float32
    output: scores   [1, 18, K] float32
            indices  [1, 18, K] flattened full-resolution indices

This runtime module intentionally does not import MIGraphX until an instance is
created, so importing modules.postprocessing remains cheap and ROCm-safe for
CPU-only paths.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, List, Tuple

import numpy as np


class MIGraphXManualCubicTopKHead:
    """Wrapper around a compiled manual-cubic resize+NMS+TopK .mxr program."""

    def __init__(self, mxr_path: str, input_name: str = "heatmaps") -> None:
        self.mxr_path = str(mxr_path)
        self.input_name = str(input_name)

        if not Path(self.mxr_path).exists():
            raise FileNotFoundError(f"Manual-cubic MIGraphX TopK .mxr not found: {self.mxr_path}")

        import migraphx  # type: ignore

        self._migraphx: Any = migraphx
        self.program = migraphx.load(self.mxr_path)

    def run(self, heatmaps_nchw: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
        heatmaps_nchw = np.ascontiguousarray(heatmaps_nchw, dtype=np.float32)

        if heatmaps_nchw.ndim != 4:
            raise ValueError(f"Expected 4D NCHW heatmaps, got {heatmaps_nchw.shape}")
        if heatmaps_nchw.shape[0] != 1:
            raise ValueError(f"This wrapper expects batch size 1, got {heatmaps_nchw.shape}")

        result = self.program.run({self.input_name: self._migraphx.argument(heatmaps_nchw)})
        if len(result) < 2:
            raise RuntimeError(f"Expected 2 outputs from manual-cubic TopK head, got {len(result)}")

        scores = np.asarray(result[0], dtype=np.float32)
        indices = np.asarray(result[1])

        c = int(heatmaps_nchw.shape[1])
        if scores.size % c != 0:
            raise RuntimeError(f"Cannot reshape scores output of size {scores.size} for C={c}")

        k = int(scores.size // c)
        scores = scores.reshape(1, c, k)
        indices = indices.reshape(1, c, k)
        return scores, indices


def topk_to_keypoint_lists(
    scores: np.ndarray,
    indices: np.ndarray,
    *,
    full_width: int,
    threshold: float = 0.1,
    num_keypoint_types: int = 18,
) -> Tuple[List[List[Tuple[float, float, float, int]]], int]:
    """Convert TopK tensors to the list format expected by group_keypoints_fast."""
    scores = np.asarray(scores, dtype=np.float32)
    indices = np.asarray(indices)

    if scores.ndim == 3:
        scores = scores[0]
    if indices.ndim == 3:
        indices = indices[0]

    channels = min(int(num_keypoint_types), int(scores.shape[0]), int(indices.shape[0]))
    all_kpts: List[List[Tuple[float, float, float, int]]] = []
    total = 0
    full_width = int(full_width)

    for kpt_idx in range(channels):
        pts: List[Tuple[float, float, float, int]] = []
        for j in range(int(scores.shape[1])):
            score = float(scores[kpt_idx, j])
            if score <= float(threshold) or score < -1.0e8:
                continue

            flat = int(indices[kpt_idx, j])
            y = flat // full_width
            x = flat - y * full_width
            pts.append((float(x), float(y), score, int(total + len(pts))))

        all_kpts.append(pts)
        total += len(pts)

    while len(all_kpts) < int(num_keypoint_types):
        all_kpts.append([])

    return all_kpts, total
